name: Deploy-Master

# Trigger the workflow on push and
# pull request events on the production branch

on:
  push:
    branches:
      - master

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd domains/u49712p46814.web0110.zxcs-klant.nl/shop.lactam.be
            php artisan down
            git pull origin master
            composer install
            php artisan migrate
            php artisan optimize
            php artisan up

