name: Deploy

# Trigger the workflow on push DEvelop

on:
  push:
    branches:
      - develop

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    name: Try to deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Packages
        run: composer install  --ignore-platform-reqs --no-dev

      - name: Enter maintenance mode or return true
      # if already is in maintenance mode
        run: (php artisan down) || true

      - name: Pull the latest version of the app
        run: git pull origin develop

      - name: Clear the old cache
        run: php artisan clear-compiled

      - name: Recreate cache
        run: php artisan optimize

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Exit maintenance mode
        run: php artisan up
